version: "3.9"
services:
  user-service:
    build: ./user-service
    ports:
      - "8001:80"
    depends_on:
      - rabbitmq
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/user_service_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
  notification-service:
    build: ./notification-service
    ports:
      - "8002:80"
    depends_on:
      - rabbitmq
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/notification_service_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_service_db,notification_service_db
    volumes:
      - ./db-data:/var/lib/mysql