doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: utf8mb4
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    default_repository_class: Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Entity'
        prefix: 'App\Infrastructure\Persistence\Doctrine\Entity'
        alias: App
