doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Migrations'
    all_or_nothing: true
    check_database_platform: true
