framework:
    messenger:
        transports:
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: messenger
                retry_strategy:
                    max_retries: 3
                    delay: 1000
        routing:
            'App\Application\Command\CreateUserCommand': amqp
        buses:
            command.bus:
                middleware:
                    - App\Application\Command\CreateUserCommandHandler
                default_middleware: true

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
