parameters:
    rabbitmq_dsn: '%env(RABBITMQ_DSN_CREATE_USER)%'
    create_user_exchange: '%env(CREATE_USER_EXCHANGE)%'
    create_user_queue_name: '%env(CREATE_USER_QUEUE_NAME)%'
    create_user_routing_key: '%env(CREATE_USER_ROUTING_KEY)%'

framework:
    messenger:
        transports:
            amqp:
                dsn: '%rabbitmq_dsn%'
                options:
                    exchange:
                        name: '%create_user_exchange%'
                        type: direct
                    queues:
                        '%create_user_queue_name%': '~'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
        routing:
            'App\Application\Command\CreateUserCommand': amqp
            'App\Application\Query\FindAllUsersQuery': amqp
        default_bus: query.bus
        buses:
            command.bus:
                middleware:
                    - App\Application\Command\CreateUserCommandHandler
            query.bus:
                middleware:
                    - validation

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
