parameters:
  rabbitmq_dsn: '%env(RABBITMQ_DSN)%'
  user_created_exchange: '%env(USER_CREATED_EXCHANGE)%'
  user_created_queue_name: '%env(USER_CREATED_QUEUE_NAME)%'

framework:
  messenger:
    transports:
      rabbitmq:
        dsn: "%rabbitmq_dsn%"
        options:
          exchange:
            name: '%user_created_exchange%'
            type: direct
          queues:
            '%user_created_queue_name%': ~
    routing:
      'App\Domain\User\Event\UserCreatedEvent': rabbitmq