framework:
  messenger:
    transports:
      rabbitmq:
        dsn: "%env(RABBITMQ_DSN)%"
        options:
          queue:
            name: "%env(QUEUE_NAME)%"
    routing:
      'App\Domain\Event\RabbitMqEvent': rabbitmq
