users_create:
    path: /users
    methods: [POST]
    controller: App\Infrastructure\Web\Controller\UserCreateController::createUser

users_list:
    path: /users
    methods: [GET]
    controller: App\Infrastructure\Web\Controller\UserGetController::getAllUsers
